name: deploy
run-name: ${{ github.actor }} start deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: terraform init
        run: terraform init
        working-directory: ./terraform
      - name: terraform validate
        run: terraform validate
        working-directory: ./terraform
      - name: terraform apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
      - name: run ansible-playbook
        run: ansible-playbook playbook.yaml
        working-directory: ./ansible
